// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCgGBDhKH2YWqPJlkZnDDlr2lMrPxjXJg',
    appId: '1:822110719007:web:8e8138f3c97da842dad92a',
    messagingSenderId: '822110719007',
    projectId: 'blocpokemonapp',
    authDomain: 'blocpokemonapp.firebaseapp.com',
    storageBucket: 'blocpokemonapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB97CczqzyEsImB4W1I42DTIOHxtMmX68o',
    appId: '1:822110719007:android:11d2682d8f5e433adad92a',
    messagingSenderId: '822110719007',
    projectId: 'blocpokemonapp',
    storageBucket: 'blocpokemonapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZF5TztlWyAwGrUIxNuC276fNfKWdXWY',
    appId: '1:822110719007:ios:5457da0825810c2cdad92a',
    messagingSenderId: '822110719007',
    projectId: 'blocpokemonapp',
    storageBucket: 'blocpokemonapp.appspot.com',
    iosClientId: '822110719007-82tb1u5slui6gem5spemi0o8majp4t62.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZF5TztlWyAwGrUIxNuC276fNfKWdXWY',
    appId: '1:822110719007:ios:5457da0825810c2cdad92a',
    messagingSenderId: '822110719007',
    projectId: 'blocpokemonapp',
    storageBucket: 'blocpokemonapp.appspot.com',
    iosClientId: '822110719007-82tb1u5slui6gem5spemi0o8majp4t62.apps.googleusercontent.com',
    iosBundleId: 'com.example.pokemonapp',
  );
}
